### ISSUE TITLE
Never call dealloc

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/QMChatViewController-ios#24]
I tried your demo and found that the view controller never call dealloc function.
You are using "self" instance in some block methods.

**Comment by Raikerian** [comment]
Hi,

Our demo project is just contains chat controller, why do you expect it to dealloc?
Although we found crash in demo project in a latest QMChatViewController, fix will for it will be available in the next release, for now use this method in viewDidLoad (if you are already using 0.3.2):

``` objective-c
[self updateDataSourceWithMessages:@[message1, message2, message3, message4]];
```

instead of:

``` objective-c
[self insertMessagesToTheBottomAnimated:@[message1, message2, message3, message4]];
```

**Comment by tranngoclinh88** [comment]
Thank @Raikerian . I'm trying to install new version but currently can not.
