### ISSUE TITLE
Crash when received offline message.

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/QMChatViewController-ios#30]
I've tried your Q-municate app in appstore and also integrate your UI in my demo app. After that, I found some crash bugs when send/received messages.
They happen when reload collection view by method performBatchUpdate without correct dataSource.
Please review and fix soon ASAP.

**Comment by Raikerian** [comment]
Hi,

We have already fixed lots of crashes about performBatchUpdate, and all of them are currently available in QMChatViewController master branch.
Also, app store version of Q-municate doesn't have any logic with performBatchUpdate, because it is using old chat controller. We are currently waiting for the app store to review our updated version.

If you have any crashes, pelase provide us crash log, or moreover the log in xcode.

**Comment by tranngoclinh88** [comment]
Thank @Raikerian . I'll check and give you my crash log if it happens.

**Comment by Raikerian** [comment]
Latest fix is available in master branch and a latest cocoapods version. For now there is no more known issues.
