### ISSUE TITLE
Crashes when pressing Send button.

### ISSUE THREAD

**Issue by rogerluan** [QuickBlox/QMChatViewController-ios#4]
When pressing the Send button, I get the following error:
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'NSConcreteMutableAttributedString initWithString:attributes:: nil value'`

Both on sample project and when tried to use in my own project.

When debugging, I noticed that it crashes when processing this line: 
`CGFloat collectionViewContentHeight = [self.collectionView.collectionViewLayout collectionViewContentSize].height;`
That's inside `scrollToBottomAnimated:` method.

Any help?

**Comment by glebus** [comment]
Hello, @rogerluan. Thanks for using QMChatViewController!

It happens because QBChatMessage object has a nil value in dateSent property. This value using as date on message bubble.

In QuickBloxSDK v.2.4 we setups this value in sendMessage:sentBlock: method. But in example project we don't use this method.

This is main reason for this problem. In your own project you should use sendMessage:sentBlock: and then add QBChatMessage object to items array.

**Comment by glebus** [comment]
Fixed Example project.
