### ISSUE TITLE
How to change the QmChatCell Design and insert the UserProfilePic and time label on top center.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/QMChatViewController-ios#41]
Hi,
I am using the QMChatViewController in my app. I want to change the design as per below screenshot. 
I am new to collection view. Before QMChatViewController, i used tableview and load the cells. like below design. Please suggest me how to display the profile pic  for the sender and how to display the time label on the top. please give sugestions.

Thank you 

![screen shot 2016-03-29 at 10 57 21 am](https://cloud.githubusercontent.com/assets/9112899/14098887/fb949fbe-f59d-11e5-91ee-216defc15f4d.png)

**Comment by Raikerian** [comment]
Hi,

As far as I understand, time label is just a section header. We have this in our controller, in order to display it for every message, set `self.chatSectionManager.timeIntervalBetweenSections` to 0.
Then just change colours for cells, use our [samples](https://github.com/QuickBlox/quickblox-ios-sdk) as example.

For user avatar in toolbar, you need to create your own toolbar and override ours one.

**Comment by Raikerian** [comment]
@ajay2c9 If you are still having any other problems or questions - feel free to let us know by creating a separate issue.
