### ISSUE TITLE
How to load the messages in the correct order using QMChatSectionManager.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/QMChatViewController-ios#45]
Hi,
I am using the UItableview for loading the chat messages. The messages are loading in reverse order.when new message is  sending it is displaying in top of all messages. I used the code like below.

``` objectivec
//.h
@property (strong, nonatomic) QMChatSectionManager *sectionmanager;

//ViewDidload
 sectionmanager=[QMChatSectionManager new];

    [[ServicesManager instance].chatService addDelegate:self];
    [ServicesManager instance].chatService.chatAttachmentService.delegate = self;

    if ([[self storedMessages] count] > 0 && sectionmanager.totalMessagesCount == 0) {
        // inserting all messages from memory storage
        NSLog(@"THE MESSAGES ARE %@",[self storedMessages]);
        [sectionmanager addMessages:[self storedMessages]];
        [chattingTable reloadData];
    }
    [self refreshMessagesShowingProgress:NO];
/////////////
- (void)refreshAndReadMessages; {

    [self refreshMessagesShowingProgress:YES];

    [self readMessages:self.unreadMessages];
    self.unreadMessages = nil;
    [chattingTable reloadData];

}
/////////////////
- (NSArray *)storedMessages
{
    return [[ServicesManager instance].chatService.messagesMemoryStorage messagesWithDialogID:self.dialog.ID];
}
//Number of sections
-(NSInteger)numberOfSectionsInTableView:(UITableView *)tableView
{
    return sectionmanager.chatSectionsCount;
}
//Number of Rows in section
-(NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
return [sectionmanager messagesCountForSectionAtIndex:section];
  }

////cell for row
-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    static NSString *cellIDentifier=@"cell";

    ChatDetailCell *cell=(ChatDetailCell *)[tableView dequeueReusableCellWithIdentifier:cellIDentifier];
    if(cell==nil)
    {
        [[NSBundle mainBundle] loadNibNamed:@"ChatDetailCell" owner:self options:nil];
        cell=self.chatCell;
    }
    NSUInteger lastSection = sectionmanager.chatSectionsCount - 1;
    if (indexPath.section == lastSection && indexPath.item == [sectionmanager messagesCountForSectionAtIndex:lastSection] - 1) {
        // the very first message
        // load more if exists
        // Getting earlier messages for chat dialog identifier.
        [[[ServicesManager instance].chatService loadEarlierMessagesWithChatDialogID:self.dialog.ID] continueWithBlock:^id(BFTask *task) {

            if ([task.result count] > 0) {
                [sectionmanager addMessages:task.result];
            }
            return nil;
        }];
    }
    // marking message as read if needed
    QBChatMessage *message = [sectionmanager messageForIndexPath:indexPath];
    [self sendReadStatusForMessage:message];
     cell. msglbl.text=message.text;
        //loading cell
return cell;
}
```

**Comment by ghost** [comment]
Hi @ajay2c9 ,

We recommend you not to use QMChatSectionManager for your own Chat View Controller.

Unfortunately, there are some reasons:
1. We wrote it for using with our collection view.
2. Our collection view is transformed upside down.

That's why in your implementation you can get some unexpected behaviour.

**Comment by ajay2c9** [comment]
How to get the all messages at a time in a array in correct order without using the QMChatSectionManager and updating the array while sending and receiving the messages.

**Comment by Raikerian** [comment]
Hi @ajay2c9 

First of all you are trying to use table view. So as I can understand you did not follow our guide [here](https://github.com/QuickBlox/QMChatViewController-ios#getting-started). You need to subclass from our QMChatViewController class in order to use all its features. With it you can easily customise such things as cells colours, font, size etc. As an example you can use our [Q-municate](https://github.com/QuickBlox/q-municate-ios) project or [Samples project](https://github.com/QuickBlox/quickblox-ios-sdk). You can also use an example our new (development is in progress) Q-municate chat view controller customised class [here](https://github.com/QuickBlox/q-municate-ios/blob/newDesign/Q-municate/Scenes/Chat/QMChatVC/QMChatVC.m) (keep in mind, it is still under development).

In your current case unfortunately there is no a perfect way for you to use our custom section manager in your own table view. It was designed specially for our collection view been transformed upside down in order for new messages being displayed at the controller push. Thats why it is adding messages in incorrect order for you, but in a perfect order for us.

If you want to develop your own chat view controller based on table view you will need to design your own chat section manager (you can also read why collection view is [better then table view for chat purposes](http://stackoverflow.com/questions/23078847/when-to-use-uicollectionview-instead-of-uitableview)).

You are also welcome to fork from our QMChatViewController repository and customise it fully inside. Our code is well documented in header files, so don't forget to read it :)

If you are still having questions feel free to ask.

**Comment by Raikerian** [comment]
Hi @ajay2c9 

First of all you are trying to use table view. So as I can understand you did not follow our guide [here](https://github.com/QuickBlox/QMChatViewController-ios#getting-started). You need to subclass from our QMChatViewController class in order to use all its features. With it you can easily customise such things as cells colours, font, size etc. As an example you can use our [Q-municate](https://github.com/QuickBlox/q-municate-ios) project or [Samples project](https://github.com/QuickBlox/quickblox-ios-sdk). You can also use an example our new (development is in progress) Q-municate chat view controller customised class [here](https://github.com/QuickBlox/q-municate-ios/blob/newDesign/Q-municate/Scenes/Chat/QMChatVC/QMChatVC.m) (keep in mind, it is still under development).

In your current case unfortunately there is no a perfect way for you to use our custom section manager in your own table view. It was designed specially for our collection view been transformed upside down in order for new messages being displayed at the controller push. Thats why it is adding messages in incorrect order for you, but in a perfect order for us.

If you want to develop your own chat view controller based on table view you will need to design your own chat section manager (you can also read why collection view is [better then table view for chat purposes](http://stackoverflow.com/questions/23078847/when-to-use-uicollectionview-instead-of-uitableview)).

You are also welcome to fork from our QMChatViewController repository and customise it fully inside. Our code is well documented in header files, so don't forget to read it :)

If you are still having questions feel free to ask.

**Comment by Raikerian** [comment]
@ajay2c9 If you are still having any other problems or questions - feel free to let us know by creating a separate issue.
